server:
  port: 8081

spring:
  application:
    name: back-rest
  datasource:
    url: jdbc:postgresql://localhost:5432/back_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  #  flyway:
  #    schemas:
  #      - public
  #      - main_schema
  #    out-of-order: true
  #    ignore-missing-migrations: true
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
