version: "3.9"

services:
  back-v1-postgres:
    image: postgres:16-alpine
    #    build:
    #      context: .
    #      dockerfile: ./docker/db/Dockerfile
    container_name: back-v1-postgres
    #    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=back_db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_PORT=5432
    volumes:
      - ./var/db/postgresql/back-v1:/var/lib/postgresql/data